spring.application.name=payflow-api

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=payflow_user
spring.datasource.password=payflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration